/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* CapSense_ISR */
#define CapSense_ISR__INTC_CORTEXM4_ASSIGNED 1
#define CapSense_ISR__INTC_CORTEXM4_PRIORITY 7u
#define CapSense_ISR__INTC_NUMBER 49u
#define CapSense_ISR_INTC_CORTEXM4_ASSIGNED 1
#define CapSense_ISR_INTC_CORTEXM4_PRIORITY 7u
#define CapSense_ISR_INTC_NUMBER 49u

/* USBFS_LowPriorityInterrupt */
#define USBFS_LowPriorityInterrupt__INTC_CORTEXM4_ASSIGNED 1
#define USBFS_LowPriorityInterrupt__INTC_CORTEXM4_PRIORITY 7u
#define USBFS_LowPriorityInterrupt__INTC_NUMBER 145u
#define USBFS_LowPriorityInterrupt_INTC_CORTEXM4_ASSIGNED 1
#define USBFS_LowPriorityInterrupt_INTC_CORTEXM4_PRIORITY 7u
#define USBFS_LowPriorityInterrupt_INTC_NUMBER 145u

/* USBFS_HighPriorityInterrupt */
#define USBFS_HighPriorityInterrupt__INTC_CORTEXM4_ASSIGNED 1
#define USBFS_HighPriorityInterrupt__INTC_CORTEXM4_PRIORITY 5u
#define USBFS_HighPriorityInterrupt__INTC_NUMBER 143u
#define USBFS_HighPriorityInterrupt_INTC_CORTEXM4_ASSIGNED 1
#define USBFS_HighPriorityInterrupt_INTC_CORTEXM4_PRIORITY 5u
#define USBFS_HighPriorityInterrupt_INTC_NUMBER 143u

/* USBFS_MediumPriorityInterrupt */
#define USBFS_MediumPriorityInterrupt__INTC_CORTEXM4_ASSIGNED 1
#define USBFS_MediumPriorityInterrupt__INTC_CORTEXM4_PRIORITY 6u
#define USBFS_MediumPriorityInterrupt__INTC_NUMBER 144u
#define USBFS_MediumPriorityInterrupt_INTC_CORTEXM4_ASSIGNED 1
#define USBFS_MediumPriorityInterrupt_INTC_CORTEXM4_PRIORITY 6u
#define USBFS_MediumPriorityInterrupt_INTC_NUMBER 144u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
